server:
  servlet:
    context-path: "/sg/microservice/v1"
  port: 8089
  
spring:
  main: 
    banner-mode: "off"
    
logging:
  level:
    org.springframework: ${LOGGING_LEVEL:INFO}
    org.mybatis: ${LOGGING_LEVEL:INFO}
    org.ehcache: ${LOGGING_LEVEL:INFO}
    com.sg: ${LOGGING_LEVEL:INFO}